configuration: Release

image: Visual Studio 2017

before_build:
  - dotnet restore Composite
  
build:
  verbosity: minimal

after_build:
  - dotnet pack Composite

artifacts:
- path: '**\*.nupkg'
  name: NuGet

deploy:
- provider: NuGet
  server: NuGet.org
  api_key:
    secure: yTJOXDOWg52hjjJFxtJNqq0uRfi8pHiC2ilKFXsJoDT6XjM13bRgvSyYaf4z9wJe
  on:
    branch: master